name: CI-Polaris-Basic
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Polaris Scan
      id: polaris-scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        polaris_application_name: ${{ github.repository_owner }}
        polaris_branch_name: ${{ github.head_ref || github.ref_name }}
        polaris_branch_parent_name: ${{ github.branch.parent.name || github.ref_name }}
        polaris_project_name: ${{ github.event.repository.name }}
        polaris_assessment_types: "SCA,SAST"
        polaris_prComment_enabled: true
        include_diagnostics: true
        polaris_server_url: ${{ vars.POLARIS_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
